### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by ProfFan** [soloturn/swift-aur#4]
`patch` should be a dev-dependency for the package

**Comment by soloturn** [comment]
done here:
* https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=swift-language-git&id=d867fb5eb974162ff4c27f2794f7a5f13d65b1e8
* https://aur.archlinux.org/cgit/aur.git/commit/?h=swift-language&id=f843ad2ed719f1e1b468bada91ae66b5aa40ed9a
